name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
     name: Build for Android
     runs-on: ubuntu-20.04

     steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Install gcc-multilib
         run: sudo apt-get install -y gcc-multilib

       - name: Install PyAudio dependencies
         run: sudo apt install portaudio19-dev python3-pyaudio
       
       - name: Install PyAudio
         run: pip install PyAudio

       - name: Build with Buildozer
         uses: ArtemSBulgakov/buildozer-action@v1
         id: buildozer
         with:
           workdir: .
           buildozer_version: stable

       - name: Upload artifacts
         uses: actions/upload-artifact@v2
         with:
           name: package
           path: ${{ steps.buildozer.outputs.filename }}
